spring.application.name=ProgettoSistemiDistribuiti

admin.setup.password=password1234
ai.setup.key = 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
server.address=0.0.0.0
server.port=8080

DBNAME=postgres
POSTGRES_USER=postgres
POSTGRES_PASSWORD=postgres

spring.datasource.url=jdbc:postgresql://localhost:5432/${DBNAME}
spring.datasource.username=${POSTGRES_USER}
spring.datasource.password=${POSTGRES_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jmx.enabled=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

jwt.secret=N9fCxZtqL2upR6VEEkY3bM8hEEGdWzE1EEEEjEEEEEEN9fCxZtqL2upR6VEEkY3bM8hEEGdWzE1EEEEjEEEEEE
jwt.expirationMs=3600000 
