spring.application.name=ProgettoSistemiDistribuiti

admin.setup.password=password1234
server.address=0.0.0.0
server.port=8080

DBNAME=postgres
POSTGRES_USER=postgres
POSTGRES_PASSWORD=postgres

spring.datasource.url=jdbc:postgresql://localhost:5432/${DBNAME}
spring.datasource.username=${POSTGRES_USER}
spring.datasource.password=${POSTGRES_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jmx.enabled=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

jwt.secret=N9fCxZtqL2upR6VEEkY3bM8hEEGdWzE1EEEEjEEEEEEN9fCxZtqL2upR6VEEkY3bM8hEEGdWzE1EEEEjEEEEEE
jwt.expirationMs=3600000 

langchain4j.ollama.chat-model.base-url=http://localhost:11434
langchain4j.ollama.chat-model.model-name=llama3
langchain4j.ollama.chat-model.timeout=PT60S