spring.application.name=ProgettoSistemiDistribuiti

server.address=0.0.0.0
server.port=8080

#
#spring.datasource.url=jdbc:postgresql://ticket-system-db.cr4emymwoeu0.eu-central-1.rds.amazonaws.com:5432/progettoticket
#spring.datasource.username=${POSTGRES_USER}
#spring.datasource.password=${POSTGRES_PASSWORD}
#spring.datasource.driver-class-name=org.postgresql.Driver
#
#spring.jmx.enabled=true
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

nlp.service.url=http://127.0.0.1:5000/api/nlp/analyze

spring.datasource.url=jdbc:postgresql://localhost:5432/${DBNAME}
spring.datasource.username=${POSTGRES_USER}
spring.datasource.password=${POSTGRES_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jmx.enabled=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


jwt.expirationMs=3600000 
